"""
50 short, varied message templates for the ImpactGuru campaign.
Each template uses {link} as the placeholder for the fundraising URL.
Tone: confident, genuine — mentions the report is verifiable in the link.
"""

TEMPLATES = [
    "Hi! Sharing a cause I genuinely believe in. This is 100% real — you can check the full report in the link and donate only if you feel it in your heart 🙏 {link}",
    "Hey! This is a genuine campaign — all details and reports are right there in the link. Check it out and contribute if it moves you 🤍 {link}",
    "I personally verified this campaign before sharing. The full report is available in the link — take a look and donate only if you feel it's right 🙏 {link}",
    "This cause is real and verified. You can check the campaign report directly in the link — every rupee goes where it's needed 💛 {link}",
    "Hi! Sharing this with full confidence — it's genuine. The report is in the link itself, go through it and donate if you feel convinced 🙏 {link}",
    "Hey! This is not a random forward — it's a verified campaign. All proof and reports are in the link. Donate only if you feel it 💙 {link}",
    "A cause I trust completely. You can verify the full report right in the link — donate whatever you feel comfortable with 🌱 {link}",
    "Hi! This campaign is 100% genuine. The link has all the details and reports — check it yourself and donate if it feels right 🙏 {link}",
    "Sharing this with confidence — it's real. You'll find the full campaign report in the link. Donate only if you're moved by it 🤍 {link}",
    "Hey! Verified and genuine. All the reports and documents are in the link — go through them and contribute if you feel it's worth it 💛 {link}",
    "Hi! This is a cause I stand behind completely. The full report is in the link — read it and donate only if you feel it in your heart ❤️ {link}",
    "This campaign is genuine — not just my word, the report speaks for itself. Check it in the link and donate if you feel it 🙏 {link}",
    "Hey! I wouldn't share something I haven't checked. This is real — the full report is in the link. Donate only if you feel it's right 🌟 {link}",
    "Hi! Sharing this with full trust — it's a verified cause. You can see all the reports in the link before you decide to donate 🙏 {link}",
    "This is genuine and I'm sharing it with confidence. The proof is in the link — check the report and donate if it moves you 💙 {link}",
    "Hey! Real cause, real impact. The full campaign report is right there in the link — see for yourself and donate if you feel it 🙏 {link}",
    "Hi! This campaign has been verified — all details are in the link. Go through the report and donate only if you feel comfortable 🤍 {link}",
    "Sharing this because I trust it completely. The campaign report is in the link — check it and donate only if you feel it's genuine 💛 {link}",
    "Hey! This is 100% real — not just a claim, you can verify the full report in the link. Donate if you feel it's worth supporting 🙏 {link}",
    "Hi! A genuine cause with a verifiable report. You'll find all the details in the link — donate only if you feel it in your heart ☕ {link}",
    "This campaign is real and the report is right there in the link. Check it yourself and donate only if you feel it's genuine 🙏 {link}",
    "Hey! I'm sharing this with full confidence it's real. The link has all the reports — go through them and donate if you feel it 💛 {link}",
    "Hi! Genuine cause, verified details. The full report is in the link — read it and contribute only if you feel it's right 🌱 {link}",
    "This is not a random message — it's a cause I believe in. The report is in the link, check it and donate if you feel moved 🙏 {link}",
    "Hey! Everything checks out — this campaign is real. You can verify the full report in the link and donate if you feel it 💪 {link}",
    "Hi! I've personally looked into this — it's genuine. The report is available right in the link. Donate only if you feel it 🙏 {link}",
    "Sharing this cause with confidence. The full details and report are in the link — check it yourself before you decide 🤍 {link}",
    "Hey! This cause is real — the report in the link will show you everything. Donate only if it moves you 🙏 {link}",
    "Hi! 100% genuine campaign. All documents and reports are available in the link — check them and donate if you feel it's right 🌅 {link}",
    "A cause worth supporting — and it's verified. The report is right there in the link. Donate only if you feel it in your heart 🙏 {link}",
    "Hey! Real people, real need. You can check the full report in the link — donate only if you feel it's genuine 😊 {link}",
    "Hi! I'm sharing this with full confidence. The link has all the proof — go through the report and donate if you feel it's right 🙏 {link}",
    "This campaign is genuine — I checked before sharing. The full report is in the link. Contribute only if you feel it 🤍 {link}",
    "Hey! Verified and real. The campaign report is right there in the link — see for yourself and donate if it moves you 💪 {link}",
    "Hi! Sharing this cause because it's genuine and urgent. You can verify the report in the link — donate only if you feel it 🙏 {link}",
    "This is a real cause with a verified report in the link. Check it yourself and donate only if you feel it's worth supporting 🌟 {link}",
    "Hey! I trust this campaign completely — the full report is in the link. Go through it and donate only if you feel it 🙏 {link}",
    "Hi! Real impact, genuine cause. The link has all the details and reports — check them and donate if you feel it's right 💛 {link}",
    "This is genuine — you have my word and the report in the link to back it up. Donate only if you feel it 🤍 {link}",
    "Hey! Sharing this cause with full confidence it's real. The report is in the link — check it and give only if you feel it 🙏 {link}",
    "Hi! Not just a forward — a verified genuine cause. The full report is right there in the link. Donate only if you feel it ❤️ {link}",
    "This is a cause I believe in deeply — and the report in the link will show you it's real. Donate if you feel it 🌱 {link}",
    "Hey! Everything is verifiable — the full report is in the link. Check it yourself and donate only if you feel it's genuine 🙏 {link}",
    "Hi! Genuine cause, real family. The link has all the reports — go through them and donate only if you feel it in your heart 💛 {link}",
    "Sharing this because it's real and it matters. The full report is in the link — check it and donate only if you feel it 🙏 {link}",
    "Hey! This campaign is legitimate — the report in the link proves it. Donate only if you feel it's worth supporting 💙 {link}",
    "Hi! I verified this before sharing. The full report is in the link — go through it and donate only if you feel it 🙏 {link}",
    "Real cause, real people, real need. The link has all the documents — check the report and donate only if you feel it 🤍 {link}",
    "Hey! This is genuine — the report in the link will confirm it. Take a look and donate only if it moves you 🙏 {link}",
    "Hi! Sharing this with complete trust it's real. The full report is in the link — read it and donate only if you feel it 🤍 {link}",
]
